# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 614)
        MainWindow.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255,255,255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.webcam_list = QtWidgets.QComboBox(self.centralwidget)
        self.webcam_list.setGeometry(QtCore.QRect(30, 40, 211, 25))
        self.webcam_list.setObjectName("webcam_list")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.streamed_video = QtWidgets.QLabel(self.centralwidget)
        self.streamed_video.setGeometry(QtCore.QRect(40, 80, 640, 480))
        self.streamed_video.setText("")
        self.streamed_video.setObjectName("streamed_video")
        self.streamButton = QtWidgets.QPushButton(self.centralwidget)
        self.streamButton.setGeometry(QtCore.QRect(260, 40, 111, 25))
        self.streamButton.setObjectName("streamButton")
        self.captureImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureImageButton.setGeometry(QtCore.QRect(380, 40, 121, 25))
        self.captureImageButton.setObjectName("captureImageButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 10, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.recordingButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordingButton.setGeometry(QtCore.QRect(520, 40, 81, 25))
        self.recordingButton.setObjectName("recordingButton")
        self.stopRecordingButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopRecordingButton.setGeometry(QtCore.QRect(608, 40, 81, 25))
        self.stopRecordingButton.setObjectName("stopRecordingButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_select_dataset = QtWidgets.QAction(MainWindow)
        self.action_select_dataset.setObjectName("action_select_dataset")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menuFile.addAction(self.action_select_dataset)
        self.menuFile.addAction(self.action_exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Face Recognition Project"))
        self.label.setText(_translate("MainWindow", "Select Webcam:"))
        self.streamButton.setText(_translate("MainWindow", "Start Stream"))
        self.captureImageButton.setText(_translate("MainWindow", "Capture Image"))
        self.label_2.setText(_translate("MainWindow", "Video Recorder:"))
        self.recordingButton.setText(_translate("MainWindow", "Start"))
        self.stopRecordingButton.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_select_dataset.setText(_translate("MainWindow", "Select Dataset"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))

